services:
  - type: web
    name: aktinyhomes-website
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate && python manage.py populate_content
    startCommand: gunicorn aktinyhomes.wsgi:application
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
    plan: free
